# Generated by Django 6.0.1 on 2026-01-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé / En préparation'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
