# Generated by Django 6.0.1 on 2026-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', "En attente d'approbation"), ('approuve', 'Approuvée / Payée'), ('livre', 'Livrée'), ('annule', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
