# Generated by Django 6.0.1 on 2026-01-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_updated_at_alter_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
